### ISSUE TITLE
GC Dashboard

### ISSUE THREAD

**Issue by svenmueller** [Mortinke/logstash-pattern#1]
Hi,

Would it be possible to share your Kibana dashboard? Or at least give some details what is shown in the screenshot (e.g. which fields are used to render the table columns and graphs etc.)

Thx a lot,
Sven

**Comment by Mortinke** [comment]
Hi Sven,

i pushed all the currently used visualizitions and dashboards in the new kibana directory, which you can import in your kibana.

**Comment by svenmueller** [comment]
Cool, thx a lot!
